import type { SiteData } from './types';

export const fallbackSite: SiteData = {
  brand: {
    name: 'Darkvampire',
    tagline: 'Cinematic photography for modern brands and timeless celebrations.',
    accent: 'Gold graphite',
    developer: {
      name: 'Abhinav Tripathi',
      url: 'https://example.com',
      email: 'hello@example.com',
      github: 'https://github.com/example',
      linkedin: 'https://linkedin.com/in/example',
      x: 'https://x.com/example',
      instagram: 'https://instagram.com/example',
      portfolio: 'https://example.com',
    },
  },
  hero: {
    eyebrow: 'Premium visual storytelling',
    headline: 'A luxury photography platform with a cinematic, editorial edge.',
    summary: 'Live content, refined motion, and a flexible content system make it ready for a premium studio launch.',
    primaryCta: { label: 'Explore Portfolio', href: '/portfolio' },
    secondaryCta: { label: 'Book a Session', href: '/booking' },
    image: 'https://images.unsplash.com/photo-1525382455947-f319bc05fb35?auto=format&fit=crop&w=1400&q=80',
  },
  stats: [
    { label: 'Editorial campaigns', value: '240+' },
    { label: 'Countries covered', value: '18' },
    { label: 'Client rating', value: '4.9/5' },
    { label: 'Awards shortlisted', value: '31' },
  ],
  categories: [
    { name: 'Wedding', slug: 'wedding', description: 'Intimate ceremonies, luminous portraits, and celebration storytelling.' },
    { name: 'Portrait', slug: 'portrait', description: 'Elegant personal branding and studio portrait sessions.' },
    { name: 'Fashion', slug: 'fashion', description: 'Editorial imagery with a cinematic, high-concept edge.' },
    { name: 'Travel', slug: 'travel', description: 'Destination narratives with immersive color and atmosphere.' },
    { name: 'Commercial', slug: 'commercial', description: 'High-conversion visuals for launches, campaigns, and products.' },
    { name: 'Fine Art', slug: 'fine-art', description: 'Minimal, expressive, gallery-ready visual essays.' },
  ],
  photos: [
    {
      id: 'p1',
      title: 'Afterglow Ceremony',
      category: 'Wedding',
      album: 'Vows at Dusk',
      location: 'Marrakesh, Morocco',
      camera: 'Sony A7R V',
      lens: '35mm f/1.4',
      iso: '640',
      aperture: 'f/2.0',
      shutter: '1/500',
      date: '2026-03-12',
      tags: ['ceremony', 'golden hour', 'editorial'],
      image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p2',
      title: 'Velvet Frame',
      category: 'Portrait',
      album: 'Private Light',
      location: 'Paradise Bay, Maldives',
      camera: 'Fujifilm GFX 100S',
      lens: '80mm f/1.7',
      iso: '320',
      aperture: 'f/1.8',
      shutter: '1/250',
      date: '2026-02-04',
      tags: ['studio', 'portrait', 'luxury'],
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p3',
      title: 'Night Runway',
      category: 'Fashion',
      album: 'Monochrome Motion',
      location: 'Paris, France',
      camera: 'Canon EOS R5',
      lens: '50mm f/1.2',
      iso: '800',
      aperture: 'f/2.8',
      shutter: '1/320',
      date: '2026-01-18',
      tags: ['fashion', 'runway', 'motion'],
      image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p4',
      title: 'Coastal Silence',
      category: 'Travel',
      album: 'Latitude Stories',
      location: 'Amalfi Coast, Italy',
      camera: 'Leica SL2',
      lens: '24-70mm',
      iso: '200',
      aperture: 'f/5.6',
      shutter: '1/1250',
      date: '2025-12-02',
      tags: ['landscape', 'travel', 'blue hour'],
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p5',
      title: 'Launch Light',
      category: 'Commercial',
      album: 'Brand Systems',
      location: 'New York, USA',
      camera: 'Sony FX3',
      lens: '24mm f/1.4',
      iso: '500',
      aperture: 'f/4.0',
      shutter: '1/160',
      date: '2026-04-22',
      tags: ['product', 'campaign', 'studio'],
      image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p6',
      title: 'Paper Moon',
      category: 'Fine Art',
      album: 'Quiet Geometry',
      location: 'Reykjavik, Iceland',
      camera: 'Hasselblad X2D',
      lens: '55mm',
      iso: '100',
      aperture: 'f/8',
      shutter: '1/200',
      date: '2025-11-09',
      tags: ['minimal', 'art', 'monochrome'],
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p7',
      title: 'Midnight Bloom',
      category: 'Fashion',
      album: 'Monochrome Motion',
      location: 'Seoul, South Korea',
      camera: 'Sony A1',
      lens: '85mm f/1.4',
      iso: '500',
      aperture: 'f/2.2',
      shutter: '1/400',
      date: '2026-01-30',
      tags: ['fashion', 'editorial', 'night'],
      image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p8',
      title: 'Glass District',
      category: 'Commercial',
      album: 'Brand Systems',
      location: 'Singapore',
      camera: 'Canon R5 C',
      lens: '24-70mm',
      iso: '200',
      aperture: 'f/5.0',
      shutter: '1/250',
      date: '2026-03-08',
      tags: ['architecture', 'branding', 'luxury'],
      image: 'https://images.unsplash.com/photo-1486326658981-ed68abe5868e?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p9',
      title: 'Sunroom Studio',
      category: 'Portrait',
      album: 'Private Light',
      location: 'Delhi, India',
      camera: 'Fujifilm X-H2S',
      lens: '56mm f/1.2',
      iso: '400',
      aperture: 'f/2.0',
      shutter: '1/320',
      date: '2026-02-25',
      tags: ['portrait', 'natural light', 'editorial'],
      image: 'https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p10',
      title: 'Harbor Frame',
      category: 'Travel',
      album: 'Latitude Stories',
      location: 'Lisbon, Portugal',
      camera: 'Leica Q3',
      lens: '28mm',
      iso: '160',
      aperture: 'f/4.5',
      shutter: '1/1600',
      date: '2025-10-21',
      tags: ['travel', 'street', 'sunlight'],
      image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p11',
      title: 'Nocturne Bloom',
      category: 'Fine Art',
      album: 'Quiet Geometry',
      location: 'Kyoto, Japan',
      camera: 'Hasselblad X2D',
      lens: '90mm',
      iso: '160',
      aperture: 'f/2.8',
      shutter: '1/320',
      date: '2026-04-06',
      tags: ['minimal', 'flower', 'shadow'],
      image: 'https://images.unsplash.com/photo-1468327768560-75b778cbb551?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'p12',
      title: 'Silver Horizon',
      category: 'Travel',
      album: 'Latitude Stories',
      location: 'Santorini, Greece',
      camera: 'Leica Q3',
      lens: '28mm',
      iso: '125',
      aperture: 'f/5.6',
      shutter: '1/1000',
      date: '2026-04-12',
      tags: ['architecture', 'travel', 'coast'],
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    },
  ],
  albums: [
    { title: 'Vows at Dusk', year: 2026, cover: 'https://images.unsplash.com/photo-1523438097201-512ae7d59f3e?auto=format&fit=crop&w=1200&q=80', count: 18, description: 'Cinematic wedding narratives captured in natural light.' },
    { title: 'Private Light', year: 2026, cover: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80', count: 26, description: 'Portrait sessions shaped by softness, contrast, and presence.' },
    { title: 'Monochrome Motion', year: 2026, cover: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80', count: 14, description: 'Fashion imagery with high contrast and deliberate movement.' },
    { title: 'Latitude Stories', year: 2025, cover: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80', count: 21, description: 'Travel editorials that balance scale, texture, and place.' },
    { title: 'Brand Systems', year: 2026, cover: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=1200&q=80', count: 16, description: 'Commercial frames designed for campaigns, product launches, and brand refreshes.' },
    { title: 'Quiet Geometry', year: 2026, cover: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&w=1200&q=80', count: 12, description: 'Fine art studies that lean on shape, silence, and negative space.' },
  ],
  services: [
    { title: 'Brand Campaigns', price: 'From $4,800', description: 'Launch-ready visual systems for premium products and brands.' },
    { title: 'Wedding Direction', price: 'From $3,200', description: 'Editorial wedding coverage with an intuitive, documentary eye.' },
    { title: 'Portrait Sessions', price: 'From $850', description: 'Studio or location portraits designed to feel timeless.' },
    { title: 'Content Retainers', price: 'Custom', description: 'Ongoing creative partnerships for social, editorial, and marketing needs.' },
  ],
  pricing: [
    { name: 'Signature', price: '$850', benefits: ['60-minute session', '20 edited photos', 'Online gallery', 'Private delivery'], highlight: false },
    { name: 'Cinematic', price: '$2,400', benefits: ['Half-day coverage', '40 edited photos', 'Priority retouching', 'Moodboard planning'], highlight: true },
    { name: 'Maison', price: 'Custom', benefits: ['Full creative direction', 'Campaign planning', 'Team coordination', 'Usage licensing'], highlight: false },
  ],
  testimonials: [
    { name: 'Aarav Mehta', role: 'Creative Director', quote: 'The entire experience felt editorial, calm, and deeply considered from first call to final delivery.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80' },
    { name: 'Isha Kapoor', role: 'Founder', quote: 'Our launch visuals looked like a luxury magazine campaign, and conversion jumped within days.', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80' },
    { name: 'Nina Laurent', role: 'Bride', quote: 'Every image felt like it belonged in a film still. We could not have asked for a better memory.', avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=400&q=80' },
  ],
  blogs: [
    { title: 'How to Build a Visual Identity That Feels Expensive', category: 'Branding', excerpt: 'A practical guide to shaping a photography brand with restraint, texture, and editorial rhythm.', date: '2026-04-01', image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Choosing the Right Light for High-End Portrait Work', category: 'Technique', excerpt: 'A compact framework for using shadow, contrast, and color to shape emotion.', date: '2026-03-14', image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1200&q=80' },
    { title: 'What Luxury Clients Expect From a Photography Website', category: 'Business', excerpt: 'From positioning to booking flow, this article covers what premium clients really notice.', date: '2026-02-28', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Designing a Gallery That Converts Visitors Into Enquiries', category: 'Experience', excerpt: 'A layout strategy for turning a portfolio into a premium sales tool without losing atmosphere.', date: '2026-03-29', image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=1200&q=80' },
    { title: 'How to Make Editorial Photography Feel Human', category: 'Creative Direction', excerpt: 'The best premium images are controlled, but never cold. Here’s how to keep the warmth.', date: '2026-03-07', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80' },
    { title: 'The Hidden Details That Sell a Luxury Brand Online', category: 'Strategy', excerpt: 'Typography, spacing, motion, and trust cues all shape premium perception.', date: '2026-02-11', image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80' },
  ],
  faqs: [
    { question: 'Can the admin update every section?', answer: 'Yes. The site content is structured so homepage copy, pricing, galleries, and blog entries can be swapped from the CMS or API layer.' },
    { question: 'Does the booking flow store submissions?', answer: 'Yes. Booking and contact submissions are persisted by the backend service and surfaced in the admin summary.' },
    { question: 'Can the portfolio work without MongoDB?', answer: 'Yes. The backend has an in-memory fallback for local development and can be switched to MongoDB Atlas with an environment variable.' },
    { question: 'Is the design responsive?', answer: 'The layout adapts across phone, tablet, and desktop with a mobile-first navigation and fluid grids.' },
  ],
  timeline: [
    { year: '2019', title: 'Studio launch', description: 'Built the first luxury portrait offering with a focus on warm, cinematic editing.' },
    { year: '2021', title: 'Brand expansion', description: 'Added commercial and editorial work for startups and fashion labels.' },
    { year: '2024', title: 'International travel', description: 'Began destination assignments across Europe, India, and the Middle East.' },
    { year: '2026', title: 'Platform rebuild', description: 'Reimagined the brand as a dynamic premium experience with a CMS-ready architecture.' },
  ],
  awards: [
    { name: 'Best Editorial Direction', issuer: 'Aperture Awards', year: 2025 },
    { name: 'Luxury Brand Storytelling', issuer: 'Creative Lens', year: 2026 },
    { name: 'Client Experience Design', issuer: 'Studio Index', year: 2026 },
  ],
  experience: [
    { label: 'Creative direction', value: '11 years' },
    { label: 'Campaigns delivered', value: '340+' },
    { label: 'Average client retention', value: '82%' },
  ],
  clients: ['Noir House', 'Maison Hale', 'Vanta Skin', 'Eclipse Atelier', 'Northstar Coffee', 'Astera Jewelry', 'Solstice Hotel', 'Velvet Lens'],
  footer: {
    address: 'Palm Court 11, Paradise Bay, Maldives',
    phone: '+91 98765 43210',
    email: 'hello@darkvampire.studio',
    hours: 'Mon - Sat, 9:00 to 18:00',
    social: {
      instagram: 'https://instagram.com/example',
      facebook: 'https://facebook.com/example',
      linkedin: 'https://linkedin.com/in/example',
      github: 'https://github.com/example',
      youtube: 'https://youtube.com/example',
      behance: 'https://behance.net/example',
      dribbble: 'https://dribbble.com/example',
      x: 'https://x.com/example',
    },
  },
};
